### ISSUE TITLE
Fatal compile error due to invalid Map access

### ISSUE THREAD

**Issue by initvector** [vanilla/jsConnectJava#9]
`jsConnect::GetJsConnectString` [retrieves the "callback" parameter](https://github.com/vanilla/jsConnectJava/blob/e9eced3ce7526822bfdf6c2c038f4d571bc810a1/src/java/com/vanillaforums/vanilla/jsConnect.java#L122) of a request, a `Map`, in order to encode it. However, it attempts to access the value using an invalid method. This causes a fatal error when compiling.

```
jsConnect.java:122: error: cannot find symbol
        request.callback =  StringEscapeUtils.escapeHtml(request.callback);
               ^
  symbol:   variable callback
  location: variable request of type Map
jsConnect.java:122: error: cannot find symbol
        request.callback =  StringEscapeUtils.escapeHtml(request.callback);
```

**Comment by tburry** [comment]
We want this changed to:

```java
request.get("callback") =  StringEscapeUtils.escapeHtml(request.callback);
```
